# Generated by Django 4.0.2 on 2022-02-28 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(default='mukesh', max_length=255)),
                ('c_email', models.CharField(max_length=255, unique=True)),
                ('c_phone', models.CharField(default='987654321', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
